### ISSUE TITLE
Hint to changelog for 1.19.3 3.2.1

### ISSUE THREAD

**Issue by myron-obsolete-account** [nonamecrackers2/cwsm-update-info#1]
Is the issue supposed to be mentioned twice in the last line?
![image](https://user-images.githubusercontent.com/53058491/228253726-96fd88c5-d9e6-4473-8c35-600b6dcd2b80.png)

Just wanted to hint you to this. If there shouldn't be any issues here then I'm sorry for making one. Have a great rest of your day.

**Comment by nonamecrackers2** [comment]
It's not no lol, thanks for catching that and letting me know
